const fs = require("fs");
const path = require("path");
const axios = require("axios");
require('dotenv').config();

// Try to load Replicate client if available
let Replicate;
try {
    Replicate = require("replicate");
} catch (e) {
    console.log("⚠️  Replicate not installed - install with: npm install replicate");
}

class VideoService {
    constructor() {
        this.uploadsDir = path.join(__dirname, '../uploads/videos');
        this.demoPath = path.join(this.uploadsDir, 'demo/sample-video.mp4');
        
        // Replicate Configuration
        this.replicateToken = process.env.REPLICATE_API_TOKEN;
        
        // Create uploads/videos directory if it doesn't exist
        if (!fs.existsSync(this.uploadsDir)) {
            fs.mkdirSync(this.uploadsDir, { recursive: true });
        }
        
        // Create demo video if not exists
        this.ensureDemoVideo();
    }

    ensureDemoVideo() {
        const demoDir = path.dirname(this.demoPath);
        if (!fs.existsSync(demoDir)) {
            fs.mkdirSync(demoDir, { recursive: true });
        }
        
        if (!fs.existsSync(this.demoPath)) {
            const ftypBox = Buffer.from([
                0x00, 0x00, 0x00, 0x20, 0x66, 0x74, 0x79, 0x70,
                0x69, 0x73, 0x6f, 0x6d, 0x00, 0x00, 0x00, 0x00,
                0x69, 0x73, 0x6f, 0x6d, 0x69, 0x73, 0x6f, 0x32,
                0x6d, 0x70, 0x34, 0x31, 0x69, 0x73, 0x6f, 0x6d
            ]);
            const videoContent = Buffer.alloc(4096, 0xFF);
            const mdatBox = Buffer.concat([
                Buffer.from([0x00, 0x00, 0x10, 0x00, 0x6d, 0x64, 0x61, 0x74]),
                videoContent
            ]);
            const videoData = Buffer.concat([ftypBox, mdatBox]);
            fs.writeFileSync(this.demoPath, videoData);
        }
    }

    async generateVideoFromReplicate(prompt, userId = null, duration = 2) {
        try {
            console.log(`🎬 Generating video with Replicate API...`);
            console.log(`   💬 Prompt: "${prompt}"`);
            console.log(`   ⏱️  Duration: ${duration}s`);
            console.log(`   ⏳ Requesting video generation...`);

            if (!Replicate) {
                throw new Error("Replicate package not installed");
            }

            const client = new Replicate({
                auth: this.replicateToken
            });

            // Using text-to-video model on Replicate (input as object with text property)
            const output = await client.run(
                "damo-vilab/text-to-video-ms-1.7b",
                {
                    input: {
                        text: prompt
                    }
                }
            );

            console.log(`   ✅ Video generated by Replicate`);

            // Download video from URL
            if (output) {
                const videoUrl = output;
                console.log(`   📥 Downloading video from: ${videoUrl}`);
                
                const response = await axios.get(videoUrl, {
                    responseType: 'arraybuffer',
                    timeout: 30000
                });
                
                return response.data;
            }

            throw new Error("No video output from Replicate");

        } catch (error) {
            console.error(`   ❌ Replicate error: ${error.message}`);
            
            if (error.message.includes('401') || error.message.includes('auth')) {
                console.error(`   🔑 API token invalid or not set`);
            } else if (error.message.includes('429')) {
                console.error(`   ⏱️  Rate limited - please wait before retrying`);
            } else if (error.message.includes('422')) {
                console.error(`   ⚠️  Input validation failed - using demo instead`);
            }
            
            throw error;
        }
    }

    async generateVideo(prompt, userId = null, duration = 2, motionStrength = 25) {
        const startTime = Date.now();
        
        try {
            console.log(`🎬 Generating video with prompt: "${prompt}"`);
            
            let videoData = null;
            let usedModel = "demo-mode";
            let isDemo = false;

            // Try Replicate first (if token is set)
            if (this.replicateToken && this.replicateToken !== 'your-replicate-token-here') {
                try {
                    videoData = await this.generateVideoFromReplicate(prompt, userId, duration);
                    usedModel = "replicate/zeroscope";
                    console.log(`   ✅ Using real video from Replicate`);
                } catch (error) {
                    console.log(`   ⚠️  Replicate failed, falling back to demo...`);
                    videoData = fs.readFileSync(this.demoPath);
                    isDemo = true;
                }
            } else {
                console.log(`   ℹ️  Replicate token not configured, using demo video...`);
                console.log(`   💡 To use real video generation, set REPLICATE_API_TOKEN in .env`);
                videoData = fs.readFileSync(this.demoPath);
                isDemo = true;
            }

            const genTime = ((Date.now() - startTime) / 1000).toFixed(2);

            // Save locally
            const timestamp = Date.now();
            const userPath = userId ? `user-${userId}` : 'anonymous';
            const filename = `video-${timestamp}.mp4`;
            const filepath = path.join(this.uploadsDir, userPath, filename);
            
            const userDir = path.dirname(filepath);
            if (!fs.existsSync(userDir)) {
                fs.mkdirSync(userDir, { recursive: true });
            }

            fs.writeFileSync(filepath, videoData);
            
            const localUrl = `/uploads/videos/${userPath}/${filename}`;
            
            console.log(`✅ Video generated successfully in ${genTime}s`);
            console.log(`📁 Saved to: ${filepath}`);
            console.log(`📊 Video size: ${(videoData.length / 1024).toFixed(2)} KB`);
            
            return {
                success: true,
                message: "Video generated successfully",
                videoUrl: localUrl,
                filename: filename,
                path: filepath,
                prompt: prompt,
                duration: parseFloat(genTime),
                size: videoData.length,
                model: usedModel,
                frames: 25,
                isDemo: isDemo
            };

        } catch (error) {
            console.error("❌ Video generation error:", error.message);
            
            throw error;
        }
    }

    async deleteVideo(filename, userId = null) {
        try {
            const userPath = userId ? `user-${userId}` : 'anonymous';
            const filepath = path.join(this.uploadsDir, userPath, filename);
            
            if (fs.existsSync(filepath)) {
                fs.unlinkSync(filepath);
                console.log(`✅ Video deleted: ${filename}`);
                return { success: true, message: "Video deleted successfully" };
            } else {
                throw new Error("Video file not found");
            }
        } catch (error) {
            console.error("❌ Delete error:", error.message);
            throw error;
        }
    }

    getVideoUrl(filename, userId = null) {
        const userPath = userId ? `user-${userId}` : 'anonymous';
        return `/uploads/videos/${userPath}/${filename}`;
    }
}

module.exports = new VideoService();
